// The signed-in Side landing, shared by the three Side surfaces.
//
// It replaces `app/views/side/shared/dashboards/show.html.erb`. Every href is generated by Rails
// and arrives resolved, so this component never composes a path from a surface name.
import Card from "@/components/ui/Card";
import Page from "@/components/ui/Page";

export type SideDashboardLink = { label: string; href: string };

export type SideDashboardSection = {
  title: string;
  links: SideDashboardLink[];
};

export type SideDashboardProps = {
  title: string;
  heading: string;
  description: string;
  sections: SideDashboardSection[];
};

export default function SideDashboard({ heading, description, sections }: SideDashboardProps) {
  return (
    <Page
      title={heading}
      description={description}
      width="wide"
    >
      {sections.map((section) => (
        <Card
          key={section.title}
          heading={section.title}
        >
          <ul className="flex flex-col gap-1">
            {section.links.map((link) => (
              <li key={link.href}>
                <a
                  href={link.href}
                  className="text-sm text-fg underline-offset-4 hover:underline"
                >
                  {link.label}
                </a>
              </li>
            ))}
          </ul>
        </Card>
      ))}
    </Page>
  );
}
