// The signed-in Side landing, shared by the three Side surfaces.
//
// It replaces `app/views/side/shared/dashboards/show.html.erb`. Every href is generated by Rails
// and arrives resolved, so this component never composes a path from a surface name.
export type SideDashboardLink = { label: string; href: string };

export type SideDashboardSection = {
  title: string;
  links: SideDashboardLink[];
};

export type SideDashboardProps = {
  title: string;
  heading: string;
  description: string;
  sections: SideDashboardSection[];
};

export default function SideDashboard({ heading, description, sections }: SideDashboardProps) {
  return (
    <section className="mx-auto flex w-full max-w-4xl flex-col gap-6 p-6">
      <h1 className="text-4xl font-bold tracking-tight">{heading}</h1>
      <p className="text-base">{description}</p>

      {sections.map((section) => (
        <section key={section.title}>
          <h2 className="text-2xl font-semibold">{section.title}</h2>
          <ul>
            {section.links.map((link) => (
              <li key={link.href}>
                <a href={link.href}>{link.label}</a>
              </li>
            ))}
          </ul>
        </section>
      ))}
    </section>
  );
}
