---
glob: "**/*.{html,text,js}{+*,}.erb"
exclude:
  - "**/vendor/**/*"
  - "**/node_modules/**/*"
linters:
  RuboCop:
    enabled: true
    rubocop_config: ".rubocop.yml"
  ParserErrors:
    enabled: true
  CommentSyntax:
    enabled: true
  ErbSafety:
    enabled: true
  SpaceAroundErbTag:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  SpaceIndentation:
    enabled: true
  ClosingErbTagIndent:
    enabled: true
  ExtraNewline:
    enabled: true
  RightTrim:
    enabled: true
  TrailingWhitespace:
    enabled: true
  FinalNewline:
    enabled: true
  NoJavascriptTagHelper:
    enabled: true
  NoUnusedDisable:
    enabled: true
  SelfClosingTag:
    enabled: true
