allowBuilds:
  puppeteer: false
minimumReleaseAge: 4320
minimumReleaseAgeIgnoreMissingTime: false
registries:
  default: https://registry.npmjs.org/
strictDepBuilds: true
trustPolicy: no-downgrade
unicode: false
overrides:
  vitest: npm:@voidzero-dev/vite-plus-test@latest
