# frozen_string_literal: true

# Sets UUID defaults for string-typed UUID primary keys. PostgreSQL 18+ uses
# uuidv7(); older PostgreSQL versions fall back to pgcrypto's gen_random_uuid().
class SetUuidv7DefaultForStringIdTables < ActiveRecord::Migration[8.2]
  # Tables with string primary keys that store UUIDs (previously generated by Rails via UuidV7PrimaryKey concern)
  STRING_UUID_TABLES = %w(
    avatars
    handles
    posts
    avatar_monikers
    avatar_memberships
    avatar_capabilities
    avatar_ownership_periods
    handle_assignments
    post_reviews
  ).freeze

  def up
    STRING_UUID_TABLES.each do |table_name|
      safety_assured do
        execute(<<~SQL.squish)
          ALTER TABLE #{table_name}
          ALTER COLUMN id SET DEFAULT #{uuid_default_function}()::text;
        SQL
      end
    end
  end

  def down
    STRING_UUID_TABLES.each do |table_name|
      safety_assured do
        execute(<<~SQL.squish)
          ALTER TABLE #{table_name}
          ALTER COLUMN id DROP DEFAULT;
        SQL
      end
    end
  end

  private

  def uuid_default_function
    select_value("SELECT to_regproc('uuidv7')").present? ? "uuidv7" : "gen_random_uuid"
  end
end
