// Shared prop shapes for the app-surface sign-in ceremony pages.
//
// Rails builds every one of these: labels are translated, URLs are generated by the router, and a
// field the ceremony does not offer is absent rather than sent and hidden.

/** A form field, carrying both its Rails parameter wrapper and its rendered `name`. */
export type SignInField = {
  /** Rails parameter wrapper, e.g. `client_email`. */
  scope: string;
  /** Attribute inside the wrapper, e.g. `address`. */
  field: string;
  /** The rendered `name` attribute, e.g. `client_email[address]`. */
  name: string;
  label: string;
  placeholder: string;
};

export type SignInLink = {
  label: string;
  href: string;
};

/** Server-rendered Turnstile configuration; only the public site key crosses. */
export type SignInTurnstile = {
  site_key: string;
  mode: "render" | "execute";
  action: string | null;
  cdata: string | null;
};
