// The first step of an email or telephone registration: submit the identifier and the consents.
//
// The form posts as an ordinary document, exactly as the ERB it replaces did, because the server
// answers a rejected submission by re-rendering this page with 422 and answers an accepted one with
// a redirect into the OTP step. Every label, description and URL arrives finished from the server;
// the Turnstile widget writes the token into the hidden field the form submits.
import TurnstileWidget, { type TurnstileWidgetProps } from "@/features/turnstile/TurnstileWidget";

import { csrfToken } from "./csrf";

export type ContactSignUpCheckbox = {
  name: string;
  label: string;
  description: string | null;
};

export type ContactSignUpFormProps = {
  title: string;
  /** Endpoint the form posts to, generated by the server. */
  action: string;
  /** Rails parameter scope, e.g. "client_email". */
  scope: string;
  field: {
    name: string;
    label: string;
    type: "email" | "tel";
    autocomplete: string;
  };
  checkboxes: ContactSignUpCheckbox[];
  /** Heading shown above the validation errors, or null when there are none. */
  error_heading: string | null;
  errors: string[];
  turnstile: TurnstileWidgetProps;
  submit_label: string;
  links: { key: string; label: string; href: string }[];
};

export default function ContactSignUpForm({
  title,
  action,
  scope,
  field,
  checkboxes,
  error_heading: errorHeading,
  errors,
  turnstile,
  submit_label: submitLabel,
  links,
}: ContactSignUpFormProps) {
  const fieldId = `${scope}_${field.name}`;

  return (
    <section>
      <h2>{title}</h2>

      <form
        action={action}
        method="post"
        data-turbo="false"
      >
        <input
          type="hidden"
          name="authenticity_token"
          value={csrfToken()}
        />

        {errorHeading ? (
          <div role="alert">
            <h3>{errorHeading}</h3>
            <ul role="list">
              {errors.map((message) => (
                <li key={message}>{message}</li>
              ))}
            </ul>
          </div>
        ) : null}

        <div>
          <label htmlFor={fieldId}>{field.label}</label>
          <input
            type={field.type}
            id={fieldId}
            name={`${scope}[${field.name}]`}
            autoComplete={field.autocomplete}
            required
          />
        </div>

        {checkboxes.map((checkbox) => (
          <div key={checkbox.name}>
            {/* Rails reads the unchecked value from the paired hidden field, as `form.check_box` did. */}
            <input
              type="hidden"
              name={`${scope}[${checkbox.name}]`}
              value="0"
            />
            <input
              type="checkbox"
              id={`${scope}_${checkbox.name}`}
              name={`${scope}[${checkbox.name}]`}
              value="1"
            />
            <label htmlFor={`${scope}_${checkbox.name}`}>{checkbox.label}</label>
            {checkbox.description ? <p>{checkbox.description}</p> : null}
          </div>
        ))}

        <div>
          <TurnstileWidget {...turnstile} />
        </div>

        <div>
          <input
            type="submit"
            value={submitLabel}
          />
        </div>
      </form>

      {links.map((link) => (
        <p key={link.key}>
          <a href={link.href}>{link.label}</a>
        </p>
      ))}
    </section>
  );
}
