// The OTP step of an email or telephone registration.
//
// The code itself never crosses the boundary: the server sends only what the page shows — the
// heading, the "we sent you a code" copy, the delivery help, and any validation message from the
// previous attempt. The form submits as an ordinary document with the verb the route expects,
// because the server answers a wrong code by re-rendering this page with 422 or 429 and a correct
// one with a redirect into the next step.
import { csrfToken } from "./csrf";

export type OtpVerificationFormProps = {
  title: string;
  description: string;
  /** Endpoint the form patches, generated by the server. */
  action: string;
  /** Rails parameter scope, e.g. "client_email". */
  scope: string;
  code_label: string;
  code_placeholder: string;
  submit_label: string;
  delivery_help: string;
  /** Heading shown above the validation errors, or null when there are none. */
  error_heading: string | null;
  errors: string[];
  return_link: { label: string; href: string };
};

export default function OtpVerificationForm({
  title,
  description,
  action,
  scope,
  code_label: codeLabel,
  code_placeholder: codePlaceholder,
  submit_label: submitLabel,
  delivery_help: deliveryHelp,
  error_heading: errorHeading,
  errors,
  return_link: returnLink,
}: OtpVerificationFormProps) {
  const fieldId = `${scope}_pass_code`;

  return (
    <section>
      <h1>{title}</h1>
      <p>{description}</p>

      <form
        action={action}
        method="post"
        data-turbo="false"
      >
        <input
          type="hidden"
          name="_method"
          value="patch"
        />
        <input
          type="hidden"
          name="authenticity_token"
          value={csrfToken()}
        />

        {errors.length > 0 ? (
          <div role="alert">
            {errorHeading ? <h2>{errorHeading}</h2> : null}
            <ul>
              {errors.map((message) => (
                <li key={message}>{message}</li>
              ))}
            </ul>
          </div>
        ) : null}

        <div>
          <label htmlFor={fieldId}>{codeLabel}</label>
          <input
            type="text"
            id={fieldId}
            name={`${scope}[pass_code]`}
            placeholder={codePlaceholder}
            // eslint-disable-next-line jsx-a11y/no-autofocus -- the ERB field carried autofocus.
            autoFocus
            autoComplete="one-time-code"
            inputMode="numeric"
            pattern="[0-9]*"
          />
        </div>

        <input
          type="submit"
          value={submitLabel}
        />
      </form>

      <p>{deliveryHelp}</p>

      <p>
        <a href={returnLink.href}>{returnLink.label}</a>
      </p>
    </section>
  );
}
