// The passcode requirement of the sign-up checkpoint.
//
// The generated passcode is shown exactly once, which is what the ERB did and why the value crosses
// the boundary at all: it is the content of the page. Nothing else about the credential travels —
// no digest, no record, no session state — and the server re-derives the credential from its own
// session when the form comes back.
import { csrfToken } from "./csrf";

export type PasscodeSetupFormProps = {
  title: string;
  description: string;
  /** Endpoint for both the save and the cancel, generated by the server. */
  action: string;
  /** Rails parameter scope, e.g. "user_secret_credential". */
  scope: string;
  checkpoint_version: number;
  errors: string[];
  name_label: string;
  secret_heading: string;
  /** The one-time passcode this page exists to display. */
  secret: string;
  one_time_notice: string;
  save_label: string;
  cancel_label: string;
};

export default function PasscodeSetupForm({
  title,
  description,
  action,
  scope,
  checkpoint_version: checkpointVersion,
  errors,
  name_label: nameLabel,
  secret_heading: secretHeading,
  secret,
  one_time_notice: oneTimeNotice,
  save_label: saveLabel,
  cancel_label: cancelLabel,
}: PasscodeSetupFormProps) {
  return (
    <section>
      <h1>{title}</h1>
      <p>{description}</p>

      <form
        action={action}
        method="post"
        data-turbo="false"
      >
        <input
          type="hidden"
          name="_method"
          value="patch"
        />
        <input
          type="hidden"
          name="authenticity_token"
          value={csrfToken()}
        />
        <input
          type="hidden"
          name="checkpoint_version"
          value={checkpointVersion}
        />

        {errors.length > 0 ? (
          <ul role="alert">
            {errors.map((message) => (
              <li key={message}>{message}</li>
            ))}
          </ul>
        ) : null}

        <div>
          <label htmlFor={`${scope}_name`}>{nameLabel}</label>
          <input
            type="text"
            id={`${scope}_name`}
            name={`${scope}[name]`}
          />
        </div>

        <input
          type="hidden"
          name={`${scope}[enabled]`}
          value="1"
        />

        <div>
          <p>{secretHeading}</p>
          <p>{secret}</p>
          <p>{oneTimeNotice}</p>
        </div>

        <input
          type="submit"
          value={saveLabel}
        />
      </form>

      <form
        action={action}
        method="post"
        data-turbo="false"
      >
        <input
          type="hidden"
          name="_method"
          value="delete"
        />
        <input
          type="hidden"
          name="authenticity_token"
          value={csrfToken()}
        />
        <button type="submit">{cancelLabel}</button>
      </form>
    </section>
  );
}
