// The confirmation step of a social sign-up: the provider identity is unknown here, so the visitor
// has to confirm that a new identity is what they want before anything is created.
//
// The Turnstile challenge is bound to this ceremony by the server, which passes the action and the
// ticket's public id as cdata and verifies both against the token it receives back.
import TurnstileWidget, { type TurnstileWidgetProps } from "@/features/turnstile/TurnstileWidget";

import { csrfToken } from "./csrf";

export type SocialSignUpConfirmationProps = {
  title: string;
  unregistered: string;
  create_identity: string;
  no_merge: string;
  cancel_if_wrong: string;
  confirm_label: string;
  submit_label: string;
  cancel_label: string;
  /** Endpoint for both the confirmation and the cancellation, generated by the server. */
  action: string;
  checkpoint_version: number;
  turnstile: TurnstileWidgetProps;
};

export default function SocialSignUpConfirmation({
  title,
  unregistered,
  create_identity: createIdentity,
  no_merge: noMerge,
  cancel_if_wrong: cancelIfWrong,
  confirm_label: confirmLabel,
  submit_label: submitLabel,
  cancel_label: cancelLabel,
  action,
  checkpoint_version: checkpointVersion,
  turnstile,
}: SocialSignUpConfirmationProps) {
  return (
    <section>
      <h1>{title}</h1>
      <p>{unregistered}</p>
      <p>{createIdentity}</p>
      <p>{noMerge}</p>
      <p>{cancelIfWrong}</p>

      <form
        action={action}
        method="post"
        data-turbo="false"
      >
        <input
          type="hidden"
          name="_method"
          value="patch"
        />
        <input
          type="hidden"
          name="authenticity_token"
          value={csrfToken()}
        />

        <TurnstileWidget {...turnstile} />

        <input
          type="hidden"
          name="checkpoint_version"
          value={checkpointVersion}
        />

        <div>
          <input
            type="checkbox"
            id="confirm_new_social_identity"
            name="confirm_new_social_identity"
            value="1"
            required
          />
          <label htmlFor="confirm_new_social_identity">{confirmLabel}</label>
        </div>

        <input
          type="submit"
          value={submitLabel}
        />
      </form>

      <form
        action={action}
        method="post"
        data-turbo="false"
      >
        <input
          type="hidden"
          name="_method"
          value="delete"
        />
        <input
          type="hidden"
          name="authenticity_token"
          value={csrfToken()}
        />
        <button type="submit">{cancelLabel}</button>
      </form>
    </section>
  );
}
