// React port of `app/views/auth/shared/_social_provider_button.html.erb`.
//
// The button posts to the surface ceremony endpoint, which hands the same POST to the OmniAuth
// request phase with a 307, so this stays an ordinary document submission rather than an Inertia
// visit: the browser has to be able to follow that 307 and then the cross-origin redirect to the
// provider.
//
// The artwork and wording are constrained by
// docs/reference/third-party-sign-in-button-requirements.md. Google renders the official button
// artwork, which carries its own English "Sign in with Google" wording, so the accessible name
// matches the artwork rather than the locale. Apple has no official whole-button artwork for the
// web, so the logo is rendered only when the official files are in the repository and the button
// otherwise carries the title alone. Any other provider renders a title-only button.
import { csrfToken } from "./csrf";

export type AppleSignInLogos = {
  white: string;
  black: string;
};

export type SocialProviderButtonProps = {
  /** "google", "apple", or another provider key. */
  provider: string;
  /** Ceremony endpoint to post to, generated by the server. */
  url: string;
  /** Button text, from the provider's permitted call-to-action list. */
  label: string;
  /** Official Apple artwork paths, or null when the artwork is not in the repository. */
  apple_logos?: AppleSignInLogos | null;
};

export default function SocialProviderButton({
  provider,
  url,
  label,
  apple_logos: appleLogos = null,
}: SocialProviderButtonProps) {
  return (
    <form
      action={url}
      method="post"
      className="social-provider-form"
      data-turbo="false"
    >
      <input
        type="hidden"
        name="authenticity_token"
        value={csrfToken()}
      />

      {provider === "google" ? (
        <button
          type="submit"
          className="social-provider-button social-provider-button--google"
          aria-label="Sign in with Google"
        >
          {/* Served straight from public/ rather than through the asset pipeline, as in the ERB. */}
          <img
            src="/images/social/google_sign_in_light.svg"
            alt=""
            width={180}
            height={40}
            className="social-provider-button__art social-provider-button__art--light"
          />
          <img
            src="/images/social/google_sign_in_dark.svg"
            alt=""
            width={180}
            height={40}
            className="social-provider-button__art social-provider-button__art--dark"
          />
        </button>
      ) : null}

      {provider === "apple" ? (
        <button
          type="submit"
          className="social-provider-button social-provider-button--apple"
        >
          {appleLogos ? (
            <>
              <img
                src={appleLogos.white}
                alt=""
                width={28}
                height={40}
                className="social-provider-button__apple-logo social-provider-button__apple-logo--white"
              />
              <img
                src={appleLogos.black}
                alt=""
                width={28}
                height={40}
                className="social-provider-button__apple-logo social-provider-button__apple-logo--black"
              />
            </>
          ) : null}
          <span className="social-provider-button__apple-title">{label}</span>
        </button>
      ) : null}

      {provider !== "google" && provider !== "apple" ? (
        <input
          type="submit"
          value={label}
          className={`social-provider-button social-provider-button--${provider}`}
        />
      ) : null}
    </form>
  );
}
