// The Rails -> React prop contract.
//
// Everything here is built by Rails and arrives already resolved: labels are translated, URLs are
// generated by the router, and the navigation a visitor may not use is absent rather than hidden.
// React renders this payload; it never re-derives it.

export type ChromeLink = {
  label: string;
  href: string;
};

export type ChromeBanner = {
  title: string | null;
  body: string;
};

export type ChromeCookieControls = {
  scope: string;
  settings_url: string;
  title: string;
  description_html: string;
  close_button: string;
  reject_all: string;
  open_settings: string;
  accept_all: string;
};

export type ChromeThemeControls = {
  hidden: boolean;
  title: string;
  description: string;
  options: {
    system: string;
    light: string;
    dark: string;
  };
};

export type SurfaceChrome = {
  family_label: string | null;
  surface: string;
  brand: { name: string; href: string };
  banner: ChromeBanner | null;
  primary_navigation: ChromeLink[] | null;
  footer_navigation: ChromeLink[] | null;
  /** Absent on the operational surfaces, which have no preference authority to link to. */
  cookie_controls: ChromeCookieControls | null;
  theme_controls: ChromeThemeControls | null;
  copyright: string;
};

/**
 * Props shared with every Inertia response of a surface. `errors` is always present because the
 * server runs with `always_include_errors_hash`, so a page can read it without a nullish guard.
 */
export type SharedProps = {
  chrome: SurfaceChrome;
  errors: Record<string, string>;
};

/** A page's own props always arrive alongside the shared ones. */
export type PageProps<T = Record<string, unknown>> = T & SharedProps;
