// The Rails -> React prop contract.
//
// Everything here is built by Rails and arrives already resolved: labels are translated, URLs are
// generated by the router, and the navigation a visitor may not use is absent rather than hidden.
// React renders this payload; it never re-derives it.

export type ChromeLink = {
  label: string;
  href: string;
};

export type ChromeBanner = {
  title: string | null;
  body: string;
};

export type ChromeCookieControls = {
  scope: string;
  settings_url: string;
  title: string;
  description_html: string;
  close_button: string;
  reject_all: string;
  open_settings: string;
  accept_all: string;
};

export type ChromeThemeControls = {
  hidden: boolean;
  title: string;
  description: string;
  options: {
    system: string;
    light: string;
    dark: string;
  };
};

export type SurfaceChrome = {
  family_label: string | null;
  surface: string;
  brand: { name: string; href: string };
  banner: ChromeBanner | null;
  primary_navigation: ChromeLink[] | null;
  footer_navigation: ChromeLink[] | null;
  /** Absent on the operational surfaces, which have no preference authority to link to. */
  cookie_controls: ChromeCookieControls | null;
  theme_controls: ChromeThemeControls | null;
  copyright: string;
};

/**
 * Props shared with every Inertia response of a surface, published to the adapter through
 * `InertiaConfig["sharedPageProps"]` in ./globals.d.ts so that a bare `usePage()` sees them.
 *
 * `errors` is deliberately absent: the adapter already declares it on `Page["props"]`, and the
 * server runs with `always_include_errors_hash`, so it is present on every response. Declaring it
 * here as well would produce a second, conflicting shape for the same payload.
 */
export type SharedProps = {
  chrome: SurfaceChrome;
};
