# typed: false
# frozen_string_literal: true

require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Live DOM reloaders mutate forms in-place and break third-party challenge
  # widgets such as Cloudflare Turnstile. Keep them opt-in for public dev hosts.
  config.hotwire.spark.enabled = ENV["HOTWIRE_SPARK_ENABLED"] == "true"

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails org:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-org.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  config.cache_store = :solid_cache_store
  config.solid_cache.connects_to = { shards: { cache: { writing: :cache, reading: :cache_replica } } }

  # Store uploaded files on the local file system (see config/storage.yml for options).
  # config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = true

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  ## Letter Opener => https://github.com/ryanb/letter_opener
  #  config.action_mailer.delivery_method = :letter_opener
  # config.action_mailer.perform_deliveries = true

  # Raise on deprecation warnings to catch issues early.
  config.active_support.deprecation = :raise

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Raise on SQL warnings from PostgreSQL (overrides :log in application.rb).
  config.active_record.db_warnings_action = :raise
  config.active_record.dump_schema_after_migration = false

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Include source location in query log tags for easier debugging
  config.active_record.query_log_tags = %i(application controller action job source_location)

  # Detect N+1 queries and raise errors immediately.
  config.active_record.strict_loading_by_default = true
  config.active_record.strict_loading_mode = :n_plus_one_only
  config.active_record.action_on_strict_loading_violation = :raise

  # Disallow deprecated .connection usage (must use .with_connection for multi-DB)
  config.active_record.permanent_connection_checkout = :deprecated

  # Raise error for missing translations.
  config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  config.generators.apply_rubocop_autocorrect_after_generate!

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  config.action_dispatch.verbose_redirect_logs = true

  # Use Solid Queue in Development.
  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.connects_to = { database: { writing: :queue, reading: :queue_replica } }

  # Enable Gzip compression
  config.middleware.use(Rack::Deflater)

  # Enable DNS rebinding protection for hosts used in route constraints.
  config.hosts.concat(
    ENV.values_at(
      "APEX_CORPORATE_URL",
      "APEX_SERVICE_URL",
      "APEX_STAFF_URL",
      "APEX_NETWORK_URL",
      "APEX_DEVELOPER_URL",
      "SIGN_CORPORATE_URL",
      "SIGN_SERVICE_URL",
      "SIGN_STAFF_URL",
      "JUMP_CORPORATE_URL",
      "JUMP_SERVICE_URL",
      "JUMP_STAFF_URL",
      "MAIN_SERVICE_URL", "MAIN_STAFF_URL", "MAIN_CORPORATE_URL",
      "CORE_SERVICE_URL", "CORE_STAFF_URL", "CORE_CORPORATE_URL",
      "DOCS_SERVICE_URL", "DOCS_STAFF_URL", "DOCS_CORPORATE_URL",
      "NEWS_SERVICE_URL", "NEWS_STAFF_URL", "NEWS_CORPORATE_URL",
      "HELP_SERVICE_URL", "HELP_STAFF_URL", "HELP_CORPORATE_URL",
    ).compact_blank,
  )

  ## file watcher
  config.file_watcher = ActiveSupport::EventedFileUpdateChecker

  ## Email Settings
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.default_url_options = { host: "localhost", port: 3001 }
  config.action_mailer.smtp_settings = {
    address: "email-smtp.#{ENV.fetch("AWS_SES_REGION", "ap-northeast-1")}.amazonaws.com",
    user_name: Rails.app.creds.option(:AWS_SES_SMTP_USERNAME),
    password: Rails.app.creds.option(:AWS_SES_SMTP_PASSWORD),
    port: 465,
    tls: true,
    authentication: :login,
    openssl_verify_mode: "peer",
    open_timeout: 5,
    read_timeout: 10,
  }

  # static file serve
  config.public_file_server.enabled = false

  # SMS Provider Configuration - Use test provider in development
  config.sms_provider = ENV.fetch("SMS_PROVIDER", "test")

  # add to the default host
  # config.action_controller.default_url_options = { host: "localhost", port: 3001 }
end
