// Shown when the actor holds no step-up factor at all: register one before the ceremony can run.
//
// Only the factors still missing are listed, and each link is generated by the server because one
// of them lives on another host.
import type { VerificationLink, VerificationMethodLink } from "./types";

export type VerificationSetupProps = {
  title: string;
  heading: string;
  description: string;
  back: VerificationLink | null;
  methods: VerificationMethodLink[];
};

export default function VerificationSetup({
  heading,
  description,
  back,
  methods,
}: VerificationSetupProps) {
  return (
    <section className="mx-auto flex w-full max-w-2xl flex-col gap-6 p-6">
      <h1>{heading}</h1>
      <p>{description}</p>

      {back ? (
        <p>
          <a href={back.href}>{back.label}</a>
        </p>
      ) : null}

      <ul>
        {methods.map((method) => (
          <li key={method.key}>
            <a href={method.href}>{method.label}</a>
          </li>
        ))}
      </ul>
    </section>
  );
}
