import NavList from "@/components/ui/NavList";
import Page from "@/components/ui/Page";

// Shown when the actor holds no step-up factor at all: register one before the ceremony can run.
//
// Only the factors still missing are listed, and each link is generated by the server because one
// of them lives on another host.
import type { VerificationLink, VerificationMethodLink } from "./types";

export type VerificationSetupProps = {
  title: string;
  heading: string;
  description: string;
  back: VerificationLink | null;
  methods: VerificationMethodLink[];
};

export default function VerificationSetup({
  heading,
  description,
  back,
  methods,
}: VerificationSetupProps) {
  return (
    <Page
      title={heading}
      description={description}
      up={back}
      width="narrow"
    >
      <NavList items={methods} />
    </Page>
  );
}
