# frozen_string_literal: true

class InsertUserIdentityPasskeyStatusesReferenceData < ActiveRecord::Migration[8.2]
  def up
    statuses = %w(
      NEYO ACTIVE USED REVOKED UNVERIFIED VERIFIED
      UNVERIFIED_WITH_SIGN_UP VERIFIED_WITH_SIGN_UP
      PRE_WITHDRAWAL_CONDITION WITHDRAWN RECORDED LOCKED
      EXPIRED CANCELED REJECTED PENDING FAILED SUCCESS
      BLOCKED WHITELISTED BLACKLISTED UNKNOWN WARNING DANGER
      SAFE MONITORING SUSPENDED DELETED REPORTED FLAGGED
      VALIDATED INVALID PROCESSING COMPLETED APPROVED RESTRICTED
      PRIVATE PUBLIC INTERNAL EXTERNAL CONFIRMED UNCONFIRMED
      ACTIVATED DEACTIVATED ENABLED DISABLED AVAILABLE UNAVAILABLE
      READY BUSY IDLE RUNNING STOPPED PAUSED STARTED FINISHED
      FAILURE ERROR OK NG YES NO ON OFF TRUE FALSE NULL
      UNDEFINED NA OTHER CUSTOM TEST NONE ALL ANY SOME FEW MANY
      HIGH MEDIUM LOW CRITICAL URGENT NORMAL MINOR MAJOR
      INFO DEBUG TRACE FATAL ALERT EMERGENCY NOTICE WARN
      ERROR_LEVEL CRITICAL_LEVEL FATAL_LEVEL EMERGENCY_LEVEL
      ALERT_LEVEL NOTICE_LEVEL INFO_LEVEL DEBUG_LEVEL TRACE_LEVEL
      NONE_LEVEL ALL_LEVEL ANY_LEVEL DEFAULT_LEVEL UNKNOWN_LEVEL
      OTHER_LEVEL CUSTOM_LEVEL TEST_LEVEL
    )

    safety_assured do
      statuses.each do |status_id|
        # No-op: intentionally left blank.
      end
    end
  end

  def down
    safety_assured do
      # No-op: intentionally left blank.
    end
  end
end
