# frozen_string_literal: true

class RenameAppPrincipalTablesToModelConventions < ActiveRecord::Migration[8.2]
  def up
    rename_table_strict :client_banners, :legacy_replaced_client_banners
    rename_table_strict :client_statuses, :legacy_replaced_client_statuses
    rename_table_strict :clients, :legacy_replaced_clients
    rename_table_strict :user_banners, :client_banners
    rename_table_strict :user_bulletins, :client_bulletins
    rename_table_strict :user_email_statuses, :client_email_statuses
    rename_table_strict :user_emails, :client_emails
    rename_table_strict :user_member_deletions, :client_member_deletions
    rename_table_strict :user_member_discoveries, :client_member_discoveries
    rename_table_strict :user_member_impersonations, :client_member_impersonations
    rename_table_strict :user_member_observations, :client_member_observations
    rename_table_strict :user_member_revocations, :client_member_revocations
    rename_table_strict :user_member_suspensions, :client_member_suspensions
    rename_table_strict :user_members, :client_members
    rename_table_strict :user_memberships, :client_memberships
    rename_table_strict :user_multi_factor_statuses, :client_multi_factor_statuses
    rename_table_strict :user_multi_factors, :client_multi_factors
    rename_table_strict :user_one_time_password_statuses, :client_one_time_password_statuses
    rename_table_strict :user_one_time_passwords, :client_one_time_passwords
    rename_table_strict :user_passkey_statuses, :client_passkey_statuses
    rename_table_strict :user_passkeys, :client_passkeys
    rename_table_strict :user_preference_currencies, :client_preference_currencies
    rename_table_strict :user_preference_currency_options, :client_preference_currency_options
    rename_table_strict :user_preference_date_format_options, :client_preference_date_format_options
    rename_table_strict :user_preference_date_formats, :client_preference_date_formats
    rename_table_strict :user_preference_densities, :client_preference_densities
    rename_table_strict :user_preference_density_options, :client_preference_density_options
    rename_table_strict :user_preference_items_per_page_options, :client_preference_items_per_page_options
    rename_table_strict :user_preference_items_per_pages, :client_preference_items_per_pages
    rename_table_strict :user_preference_language_options, :client_preference_language_options
    rename_table_strict :user_preference_languages, :client_preference_languages
    rename_table_strict :user_preference_motion_options, :client_preference_motion_options
    rename_table_strict :user_preference_motions, :client_preference_motions
    rename_table_strict :user_preference_region_options, :client_preference_region_options
    rename_table_strict :user_preference_regions, :client_preference_regions
    rename_table_strict :user_preference_theme_options, :client_preference_theme_options
    rename_table_strict :user_preference_themes, :client_preference_themes
    rename_table_strict :user_preference_time_format_options, :client_preference_time_format_options
    rename_table_strict :user_preference_time_formats, :client_preference_time_formats
    rename_table_strict :user_preference_timezone_options, :client_preference_timezone_options
    rename_table_strict :user_preference_timezones, :client_preference_timezones
    rename_table_strict :user_preferences, :client_preferences
    rename_table_strict :user_secret_kinds, :client_secret_kinds
    rename_table_strict :user_secret_statuses, :client_secret_statuses
    rename_table_strict :user_secrets, :client_secrets
    rename_table_strict :user_social_apple_statuses, :client_social_apple_statuses
    rename_table_strict :user_social_apples, :client_social_apples
    rename_table_strict :user_social_google_statuses, :client_social_google_statuses
    rename_table_strict :user_social_googles, :client_social_googles
    rename_table_strict :user_statuses, :client_statuses
    rename_table_strict :user_telephone_statuses, :client_telephone_statuses
    rename_table_strict :user_telephones, :client_telephones
    rename_table_strict :user_visibilities, :client_visibilities
    rename_table_strict :users, :clients
  end

  def down
    rename_table_strict :clients, :users
    rename_table_strict :client_visibilities, :user_visibilities
    rename_table_strict :client_telephones, :user_telephones
    rename_table_strict :client_telephone_statuses, :user_telephone_statuses
    rename_table_strict :client_statuses, :user_statuses
    rename_table_strict :client_social_googles, :user_social_googles
    rename_table_strict :client_social_google_statuses, :user_social_google_statuses
    rename_table_strict :client_social_apples, :user_social_apples
    rename_table_strict :client_social_apple_statuses, :user_social_apple_statuses
    rename_table_strict :client_secrets, :user_secrets
    rename_table_strict :client_secret_statuses, :user_secret_statuses
    rename_table_strict :client_secret_kinds, :user_secret_kinds
    rename_table_strict :client_preferences, :user_preferences
    rename_table_strict :client_preference_timezones, :user_preference_timezones
    rename_table_strict :client_preference_timezone_options, :user_preference_timezone_options
    rename_table_strict :client_preference_time_formats, :user_preference_time_formats
    rename_table_strict :client_preference_time_format_options, :user_preference_time_format_options
    rename_table_strict :client_preference_themes, :user_preference_themes
    rename_table_strict :client_preference_theme_options, :user_preference_theme_options
    rename_table_strict :client_preference_regions, :user_preference_regions
    rename_table_strict :client_preference_region_options, :user_preference_region_options
    rename_table_strict :client_preference_motions, :user_preference_motions
    rename_table_strict :client_preference_motion_options, :user_preference_motion_options
    rename_table_strict :client_preference_languages, :user_preference_languages
    rename_table_strict :client_preference_language_options, :user_preference_language_options
    rename_table_strict :client_preference_items_per_pages, :user_preference_items_per_pages
    rename_table_strict :client_preference_items_per_page_options, :user_preference_items_per_page_options
    rename_table_strict :client_preference_density_options, :user_preference_density_options
    rename_table_strict :client_preference_densities, :user_preference_densities
    rename_table_strict :client_preference_date_formats, :user_preference_date_formats
    rename_table_strict :client_preference_date_format_options, :user_preference_date_format_options
    rename_table_strict :client_preference_currency_options, :user_preference_currency_options
    rename_table_strict :client_preference_currencies, :user_preference_currencies
    rename_table_strict :client_passkeys, :user_passkeys
    rename_table_strict :client_passkey_statuses, :user_passkey_statuses
    rename_table_strict :client_one_time_passwords, :user_one_time_passwords
    rename_table_strict :client_one_time_password_statuses, :user_one_time_password_statuses
    rename_table_strict :client_multi_factors, :user_multi_factors
    rename_table_strict :client_multi_factor_statuses, :user_multi_factor_statuses
    rename_table_strict :client_memberships, :user_memberships
    rename_table_strict :client_members, :user_members
    rename_table_strict :client_member_suspensions, :user_member_suspensions
    rename_table_strict :client_member_revocations, :user_member_revocations
    rename_table_strict :client_member_observations, :user_member_observations
    rename_table_strict :client_member_impersonations, :user_member_impersonations
    rename_table_strict :client_member_discoveries, :user_member_discoveries
    rename_table_strict :client_member_deletions, :user_member_deletions
    rename_table_strict :client_emails, :user_emails
    rename_table_strict :client_email_statuses, :user_email_statuses
    rename_table_strict :client_bulletins, :user_bulletins
    rename_table_strict :client_banners, :user_banners
    rename_table_strict :legacy_replaced_clients, :clients
    rename_table_strict :legacy_replaced_client_statuses, :client_statuses
    rename_table_strict :legacy_replaced_client_banners, :client_banners
  end
end
